- name: Golang
  logo: go
  url: https://golang.org/
  color: '#7FD6EA'
  projects:
    - url: https://github.com/arielsrv/golang-toolkit
    - url: https://github.com/arielsrv/pets-api
    - url: https://github.com/arielsrv/golang-template

- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/arielstv/pets-cli
